import { PublicPlace, UserSavedPlace } from "../types";

export const INITIAL_PUBLIC_PLACES: PublicPlace[] = [
  {
    placeId: "ChIJ_medan_tiptop",
    name: "Tip Top Restaurant & Bakery",
    address: "Jl. Jend. Ahmad Yani No. 92 A-B, Kesawan, Medan",
    city: "Medan",
    lat: 3.5878,
    lng: 98.6817,
    rating: 4.7,
    saveCount: 88,
    topDishes: ["Bistik Lidah Sapi (Ox Tongue)", "Kue Moorkop & Bitterballen", "Homemade Ice Cream Tip Top"],
    tags: ["Legendary", "Peranakan", "Since 1934", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=tip%20top%20restaurant%20medan",
    vibesOrSummary: "Historic colonial dining hall serving century-old recipes baked in authentic 1934 wood-fired brick ovens.",
  },
  {
    placeId: "ChIJ_aceh_mie_razali",
    name: "Mie Razali",
    address: "Jl. Panglima Polem No. 83-85, Peunayong, Banda Aceh",
    city: "Banda Aceh",
    lat: 5.5564,
    lng: 95.3218,
    rating: 4.8,
    saveCount: 92,
    topDishes: ["Mie Aceh Kepiting Jumbo", "Mie Aceh Daging Kuah Kental", "Es Timun Serut"],
    tags: ["Legendary", "Spicy", "Since 1967", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=mie%20razali%20banda%20aceh",
    vibesOrSummary: "The undisputed crown jewel of Acehnese curried noodles, brimming with fresh sea crab and fragrant cardamom.",
  },
  {
    placeId: "ChIJ_padang_lamun_ombak",
    name: "Rumah Makan Lamun Ombak",
    address: "Jl. Khatib Sulaiman No. 99, Ulak Karang, Padang",
    city: "Padang",
    lat: -0.9163,
    lng: 100.3582,
    rating: 4.9,
    saveCount: 124,
    topDishes: ["Ayam Pop Minyak Kelapa", "Gulai Otak Sapi", "Rendang Daging Sapi Hitam"],
    tags: ["Legendary", "Halal", "Nasi Padang", "Viral TikTok"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=lamun%20ombak%20padang",
    vibesOrSummary: "Sublime authentic Minangkabau feast featuring melt-in-the-mouth Ayam Pop and deeply caramelized dark beef rendang.",
  },
  {
    placeId: "ChIJ_palembang_pempek_vico",
    name: "Pempek Vico Palembang",
    address: "Jl. Letkol Iskandar No. 541-542, 24 Ilir, Palembang",
    city: "Palembang",
    lat: -2.9836,
    lng: 104.7578,
    rating: 4.8,
    saveCount: 85,
    topDishes: ["Pempek Kapal Selam Telur", "Pempek Kulit Crispy", "Kuah Cuko Kental Pedas"],
    tags: ["Legendary", "Seafood", "Street Food", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=pempek%20vico%20palembang",
    vibesOrSummary: "Crisp golden Tenggiri fish cakes drenched in dark, tangy Aren sugar cuko infused with bird's eye chilies and garlic.",
  },
  {
    placeId: "ChIJ_belitung_mie_atep",
    name: "Mie Belitung Atep",
    address: "Jl. Sriwijaya No. 27, Parit, Tanjung Pandan, Belitung",
    city: "Belitung",
    lat: -2.7383,
    lng: 107.6322,
    rating: 4.7,
    saveCount: 64,
    topDishes: ["Mie Belitung Kuah Udang", "Es Jeruk Kunci Asli", "Emping Melinjo Kuah"],
    tags: ["Legendary", "Seafood", "Heritage", "Hidden Gem"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=mie%20atep%20belitung",
    vibesOrSummary: "Silky yellow noodles bathing in a comforting sweet-savory shrimp broth garnished with boiled potato cubes and cucumber.",
  },
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    saveCount: 110,
    topDishes: ["Gulai Sapi Campur", "Gulai Sapi Daging", "Kerupuk Kulit Kuah"],
    tags: ["Street Food", "Viral TikTok", "Late Night", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    vibesOrSummary: "Legendary late-night street-side beef curry in Blok M with rich, aromatic spiced coconut broth served over warm rice.",
  },
  {
    placeId: "ChIJ22_nasgor_kebonsirih",
    name: "Nasi Goreng Kambing Kebon Sirih",
    address: "Jl. Kebon Sirih No. 3, Menteng, Jakarta Pusat",
    city: "Jakarta",
    lat: -6.1834,
    lng: 106.8302,
    rating: 4.6,
    saveCount: 82,
    topDishes: ["Nasi Goreng Kambing Jumbo", "Sate Kambing Bumbu Kecap", "Acar Timun & Emping"],
    tags: ["Street Food", "Legendary", "Halal", "Late Night"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=nasi%20goreng%20kambing%20kebon%20sirih",
    vibesOrSummary: "Giant street-side woks tossing fragrant fried rice infused with rich ghee (minyak samin), cloves, and tender mutton chunks.",
  },
  {
    placeId: "ChIJ_jakarta_es_tak_kie",
    name: "Kopi Es Tak Kie Glodok",
    address: "Jl. Pintu Besar Selatan III No. 4-6, Glodok, Pinangsia, Jakarta Barat",
    city: "Jakarta",
    lat: -6.1418,
    lng: 106.8142,
    rating: 4.7,
    saveCount: 73,
    topDishes: ["Es Kopi Susu Tradisional", "Es Kopi Hitam O", "Pangsit Kuah Vintage"],
    tags: ["Heritage", "Since 1927", "Glodok", "Coffee"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=kopi%20es%20tak%20kie%20glodok",
    vibesOrSummary: "Centuries-old Chinatown kopitiam pouring robust Robusta blends with condensed milk in an authentic vintage alley atmosphere.",
  },
  {
    placeId: "ChIJ_bogor_toge_gebro",
    name: "Toge Goreng H. Gebro",
    address: "Pasar Anyar, Blok C. No. 3, Jl. Pengadilan, Kota Bogor",
    city: "Bogor",
    lat: -6.5937,
    lng: 106.7925,
    rating: 4.8,
    saveCount: 58,
    topDishes: ["Toge Goreng Bumbu Tauco", "Kupat Tahu Oncom", "Kerupuk Mie Kuning"],
    tags: ["Legendary", "Since 1943", "Street Food", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=toge%20goreng%20h%20gebro%20bogor",
    vibesOrSummary: "Steamed fresh bean sprouts, yellow noodles, and rice cakes smothered in a savory fermented tauco and red oncom gravy.",
  },
  {
    placeId: "ChIJ_bandung_batagor_kingsley",
    name: "Batagor Kingsley",
    address: "Jl. Veteran No. 25, Kebon Pisang, Sumur Bandung, Bandung",
    city: "Bandung",
    lat: -6.9189,
    lng: 107.6163,
    rating: 4.8,
    saveCount: 104,
    topDishes: ["Batagor Goreng Spesial", "Batagor Kuah Baso", "Siomay Kukus Tenggiri"],
    tags: ["Legendary", "Street Food", "Bandung", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=batagor%20kingsley%20bandung",
    vibesOrSummary: "Crunchy deep-fried mackerel fish dumplings served with rich roasted peanut sauce, sweet soy, and a squeeze of fragrant kaffir lime.",
  },
  {
    placeId: "ChIJ_bandung_cuanki_serayu",
    name: "Cuanki Serayu",
    address: "Jl. Serayu No. 2, Cihapit, Bandung Wetan, Bandung",
    city: "Bandung",
    lat: -6.9085,
    lng: 107.6273,
    rating: 4.7,
    saveCount: 98,
    topDishes: ["Bakso Cuanki Komplit", "Batagor Kuah Bening", "Siomay Rebus Cuanki"],
    tags: ["Viral TikTok", "Comfort Food", "Street Food", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=cuanki%20serayu%20bandung",
    vibesOrSummary: "Bandung's most viral soup bowl filled with delicate wontons, fried tofu, and beef meatballs in a steaming broth.",
  },
  {
    placeId: "ChIJ33_sate_maranggi_yetty",
    name: "Sate Maranggi Hj. Yetty Cibungur",
    address: "Jl. Raya Cibungur, Bungursari, Kabupaten Purwakarta",
    city: "Purwakarta",
    lat: -6.4715,
    lng: 107.4721,
    rating: 4.8,
    saveCount: 89,
    topDishes: ["Sate Maranggi Sapi Empuk", "Sambal Tomat Rawit Segar", "Es Kelapa Kopyor"],
    tags: ["Legendary", "Roadtrip", "Halal", "Viral TikTok"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=sate%20maranggi%20hj%20yetty",
    vibesOrSummary: "Sweet coriander and galangal-marinated beef skewers grilled over open charcoal and paired with zesty diced tomato sambal.",
  },
  {
    placeId: "ChIJ55_gudeg_yudjum",
    name: "Gudeg Yu Djum Wijilan 167",
    address: "Jl. Wijilan No. 167, Panembahan, Kraton, Yogyakarta",
    city: "Yogyakarta",
    lat: -7.8049,
    lng: 110.3664,
    rating: 4.8,
    saveCount: 115,
    topDishes: ["Nasi Gudeg Kering Komplit", "Sambal Goreng Krecek Pedas", "Ayam Kampung Areh Gurih"],
    tags: ["Traditional", "Legendary", "Halal", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gudeg%20yu%20djum%20wijilan",
    vibesOrSummary: "The royal cradle of authentic dry gudeg, slow-braised for hours with young jackfruit and teakwood leaves over charcoal.",
  },
  {
    placeId: "ChIJ_jogja_kopi_klothok",
    name: "Warung Kopi Klothok Pakem",
    address: "Jl. Kaliurang KM 16, Area Sawah, Pakembinangun, Sleman, Yogyakarta",
    city: "Yogyakarta",
    lat: -7.6713,
    lng: 110.4215,
    rating: 4.8,
    saveCount: 122,
    topDishes: ["Pisang Goreng Crispy Tepung", "Sayur Lodeh Kluwih & Terong", "Kopi Klothok Tubruk Arang"],
    tags: ["Viral TikTok", "View", "Traditional", "Breakfast"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=kopi%20klothok%20jogja",
    vibesOrSummary: "Idyllic open-air Javanese countryside feast serving piping hot banana fritters and homestyle hearth cooking right beside rice paddies.",
  },
  {
    placeId: "ChIJ_semarang_loenpia_gang_lombok",
    name: "Loenpia Gang Lombok No. 11",
    address: "Gang Lombok No. 11, Purwodinatan, Semarang Tengah, Semarang",
    city: "Semarang",
    lat: -6.9745,
    lng: 110.4285,
    rating: 4.8,
    saveCount: 87,
    topDishes: ["Loenpia Basah Spesial", "Loenpia Goreng Renyah", "Saus Bawang Kental & Daun Bawang"],
    tags: ["Legendary", "Since 1800s", "Chinatown", "Heritage"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=loenpia%20gang%20lombok%20semarang",
    vibesOrSummary: "Semarang's historic bamboo-shoot spring roll shrine next to Tay Kak Sie temple, stuffed with tender prawns and fresh crab meat.",
  },
  {
    placeId: "ChIJ_solo_timlo_sastro",
    name: "Timlo Sastro Pasar Gede",
    address: "Jl. Pasar Gede Timur No. 1-2, Baluwarti, Pasar Kliwon, Surakarta (Solo)",
    city: "Solo",
    lat: -7.5694,
    lng: 110.8322,
    rating: 4.7,
    saveCount: 76,
    topDishes: ["Timlo Komplit Telur Ati", "Sosis Solo Goreng Basah", "Sup Bening Kuah Kaldu Ayam"],
    tags: ["Legendary", "Since 1952", "Comfort Food", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=timlo%20sastro%20solo",
    vibesOrSummary: "Heartwarming clear chicken broth filled with shredded chicken, rolled egg pancakes (sosis Solo), and braised herbal duck eggs.",
  },
  {
    placeId: "ChIJ11_bebek_sinjay",
    name: "Bebek Sinjay Madura",
    address: "Jl. Rungkut Madya No. 133, Rungkut Kidul, Surabaya",
    city: "Surabaya",
    lat: -7.3235,
    lng: 112.7844,
    rating: 4.8,
    saveCount: 108,
    topDishes: ["Bebek Goreng Kremes Renyah", "Sambal Pencit Mangga Muda", "Nasi Hangat Daun Pisang"],
    tags: ["Spicy", "Viral TikTok", "Halal", "Comfort Food"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=bebek%20sinjay%20surabaya",
    vibesOrSummary: "Irresistibly crispy fried spiced duck smothered in fragrant spiced crumbs and accompanied by fiery sour shredded young mango sambal.",
  },
  {
    placeId: "ChIJ_surabaya_rawon_setan",
    name: "Rawon Setan Embong Malang",
    address: "Jl. Embong Malang No. 78/I, Genteng, Surabaya",
    city: "Surabaya",
    lat: -7.2605,
    lng: 112.7412,
    rating: 4.7,
    saveCount: 94,
    topDishes: ["Rawon Daging Sapi Kuah Hitam", "Telur Asin & Tauge Pendek", "Empal Goreng Bumbu Gurih"],
    tags: ["Legendary", "Spicy", "Late Night", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=rawon%20setan%20surabaya",
    vibesOrSummary: "The legendary midnight pioneer of jet-black beef soup enriched with fermented kluwek nuts and fiery sambal terasi.",
  },
  {
    placeId: "ChIJ_malang_bakso_president",
    name: "Bakso President Malang",
    address: "Jl. Batanghari No. 5, Rampal Celaket, Klojen, Kota Malang",
    city: "Malang",
    lat: -7.9625,
    lng: 112.6375,
    rating: 4.7,
    saveCount: 86,
    topDishes: ["Bakso Campur Pangsit Goreng", "Bakso Urat & Bakso Bakar", "Kuah Kaldu Sumsum Bening"],
    tags: ["Viral TikTok", "Unique Vibe", "Legendary", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=bakso%20president%20malang",
    vibesOrSummary: "Unbeatable culinary thrill dining on crisp wontons and bouncy beef meatballs merely inches away from roaring train tracks.",
  },
  {
    placeId: "ChIJ_banyuwangi_sego_tempong",
    name: "Sego Tempong Mbok Wah",
    address: "Jl. Gembrung No. 220, Glagah, Bakungan, Banyuwangi",
    city: "Banyuwangi",
    lat: -8.2144,
    lng: 114.3482,
    rating: 4.8,
    saveCount: 79,
    topDishes: ["Nasi Tempong Ikan Laut Goreng", "Sambal Tempong Ulek Tomat Ranti", "Sayur Bayam & Labu Rebus"],
    tags: ["Spicy", "Seafood", "Street Food", "Legendary"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=sego%20tempong%20mbok%20wah",
    vibesOrSummary: "Fierce, freshly pounded chili sambal using heirloom ranti tomatoes served alongside sweet boiled vegetables and crispy fried marine catches.",
  },
  {
    placeId: "ChIJ44_warung_mak_beng",
    name: "Warung Mak Beng Sanur",
    address: "Jl. Hang Tuah No. 45, Sanur, Denpasar Selatan, Bali",
    city: "Bali",
    lat: -8.6758,
    lng: 115.2631,
    rating: 4.9,
    saveCount: 135,
    topDishes: ["Sup Kepala Ikan Bumbu Kuning", "Ikan Laut Goreng Sambal Terasi", "Nasi Putih Hangat"],
    tags: ["Legendary", "Seafood", "Since 1941", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=warung%20mak%20beng%20sanur",
    vibesOrSummary: "World-celebrated seaside shack serving a solitary, perfected menu since 1941: tangy starfruit fish soup and crackling deep-fried fish.",
  },
  {
    placeId: "ChIJ_bali_bebek_bengil",
    name: "Bebek Bengil Dirty Duck Diner",
    address: "Jl. Hanoman, Padangtegal, Kecamatan Ubud, Kabupaten Gianyar, Bali",
    city: "Bali",
    lat: -8.5186,
    lng: 115.2642,
    rating: 4.7,
    saveCount: 91,
    topDishes: ["Original Crispy Duck", "Sambal Matah Khas Bali", "Nasi Campur Bebek Bengil"],
    tags: ["Legendary", "Ubud", "View", "Heritage"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=bebek%20bengil%20ubud",
    vibesOrSummary: "Ubud's pioneer of crispy spiced duck cooked with aromatic Balinese base genep spices overlooking tranquil emerald rice fields.",
  },
  {
    placeId: "ChIJ_lombok_ayam_taliwang",
    name: "Ayam Taliwang H. Moerad",
    address: "Jl. Pelikan No. 6, Pejanggik, Mataram, Nusa Tenggara Barat",
    city: "Lombok",
    lat: -8.5833,
    lng: 116.1264,
    rating: 4.8,
    saveCount: 84,
    topDishes: ["Ayam Taliwang Bakar Madu Pedas", "Plecing Kangkung Sambal Terasi", "Beberuk Terong Segar"],
    tags: ["Legendary", "Spicy", "Halal", "Nusantara"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=ayam%20taliwang%20h%20moerad",
    vibesOrSummary: "Fiery charcoal-grilled spring chicken basted with shrimp paste, chilies, and wild shallots accompanied by crisp water spinach plecing.",
  },
  {
    placeId: "ChIJ_pontianak_kopi_asiang",
    name: "Warung Kopi Asiang",
    address: "Jl. Merapi No. 01, Benua Melayu Darat, Pontianak Selatan, Pontianak",
    city: "Pontianak",
    lat: -0.0267,
    lng: 109.3402,
    rating: 4.8,
    saveCount: 89,
    topDishes: ["Kopi Susu Tarik Hainan", "Roti Srikaya Panggang Arang", "Telur Setengah Matang Kampung"],
    tags: ["Legendary", "Since 1958", "Breakfast", "Coffee"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=kopi%20asiang%20pontianak",
    vibesOrSummary: "Iconic open-counter Hainanese coffee temple where the celebrated master barista pours rich pulled Robusta and homemade coconut jam toast.",
  },
  {
    placeId: "ChIJ_banjarmasin_soto_bang_amat",
    name: "Soto Banjar Bang Amat",
    address: "Jl. Banua Anyar No. 56, Banjarmasin Timur, Banjarmasin",
    city: "Banjarmasin",
    lat: -3.3151,
    lng: 114.6133,
    rating: 4.8,
    saveCount: 88,
    topDishes: ["Soto Banjar Komplit Suwir Ayam", "Sate Ayam Kuah Manis", "Perkedel Singkong & Telur Bebek"],
    tags: ["Legendary", "Riverview", "Halal", "Traditional"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=soto%20banjar%20bang%20amat",
    vibesOrSummary: "Scenic Martapura riverfront pavilion dishing out aromatic chicken soup perfumed with cinnamon, nutmeg, and creamy evaporated milk.",
  },
  {
    placeId: "ChIJ_balikpapan_kepiting_dandito",
    name: "Kepiting Dandito",
    address: "Jl. Marsma R. Iswahyudi No. 70, Gunung Bahagia, Balikpapan Selatan",
    city: "Balikpapan",
    lat: -1.2586,
    lng: 116.8928,
    rating: 4.8,
    saveCount: 97,
    topDishes: ["Kepiting Saus Dandito Spesial", "Kepiting Lada Hitam Pedas", "Mantau Goreng Renyah"],
    tags: ["Viral TikTok", "Seafood", "Legendary", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=kepiting%20dandito%20balikpapan",
    vibesOrSummary: "Colossal mangrove mud crabs smothered in glossy sweet-spicy signature sauce best devoured with fluffy golden fried mantau buns.",
  },
  {
    placeId: "ChIJ_makassar_coto_nusantara",
    name: "Coto Nusantara Makassar",
    address: "Jl. Nusantara No. 32, Pattunuang, Wajo, Kota Makassar",
    city: "Makassar",
    lat: -5.1278,
    lng: 119.4089,
    rating: 4.9,
    saveCount: 118,
    topDishes: ["Coto Daging Sapi Kuah Kacang", "Ketupat Daun Pandan", "Es Pisang Ijo Khas Makassar"],
    tags: ["Legendary", "Halal", "Street Food", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=coto%20nusantara%20makassar",
    vibesOrSummary: "Makassar's quintessential spiced beef broth stewed with 40 botanical spices, ground roasted peanuts, and served with savory woven ketupat.",
  },
  {
    placeId: "ChIJ_manado_raja_oci",
    name: "RM Raja Oci Manado",
    address: "Jl. Sudirman No. 85, Pinaesaan, Wenang, Kota Manado",
    city: "Manado",
    lat: 1.4883,
    lng: 124.8436,
    rating: 4.8,
    saveCount: 93,
    topDishes: ["Oci Bakar Bumbu Rica", "Kangkung Cah Bunga Pepaya", "Sambal Dabu-Dabu Lilang Segar"],
    tags: ["Seafood", "Spicy", "Halal Friendly", "Legendary"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=raja%20oci%20manado",
    vibesOrSummary: "Charcoal-grilled yellowtail oceanic mackerel paired with fiery citrus dabu-dabu salsa and sauteed papaya blossom greens.",
  },
];

export const INITIAL_USER_SAVED_PLACES: UserSavedPlace[] = [
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    tasteRating: 5,
    visited: true,
    visitedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    recommendedDishes: ["Gulai Sapi Telur", "Kerupuk Kulit Kuah"],
    estimatedPrice: "Rp 15,000 - Rp 30,000",
    tags: ["Street Food", "Viral TikTok", "Late Night"],
    personalNotes: "Arrive before 8 PM to avoid the office rush hour lines. The savory spiced coconut broth is incredible paired with crispy crackers!",
    savedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    vibesOrSummary: "Legendary late-night street-side beef curry in Blok M with rich, aromatic spiced coconut broth served over warm rice.",
  },
  {
    placeId: "ChIJ22_nasgor_kebonsirih",
    name: "Nasi Goreng Kambing Kebon Sirih",
    address: "Jl. Kebon Sirih No. 3, Menteng, Jakarta Pusat",
    city: "Jakarta",
    lat: -6.1834,
    lng: 106.8302,
    rating: 4.6,
    tasteRating: 5,
    visited: false, // Wishlist
    sourceUrl: "https://www.tiktok.com/search?q=nasi%20goreng%20kambing%20kebon%20sirih",
    recommendedDishes: ["Nasi Goreng Kambing Jumbo", "Sate Kambing Bumbu Kecap"],
    estimatedPrice: "Rp 45,000 - Rp 70,000",
    tags: ["Street Food", "Legendary", "Halal", "Late Night"],
    personalNotes: "Saved on wishlist for late night craving! Must try the aromatic mutton fried rice cooked in giant woks with ghee (minyak samin).",
    savedAt: new Date(Date.now() - 86400000).toISOString(),
    vibesOrSummary: "Giant street-side woks tossing fragrant fried rice infused with rich ghee (minyak samin), cloves, and tender mutton chunks.",
  },
];

export const CITIES = [
  "All Cities",
  "Jakarta",
  "Bandung",
  "Yogyakarta",
  "Surabaya",
  "Bali",
  "Lombok",
  "Medan",
  "Padang",
  "Banda Aceh",
  "Palembang",
  "Semarang",
  "Solo",
  "Malang",
  "Banyuwangi",
  "Belitung",
  "Pontianak",
  "Banjarmasin",
  "Balikpapan",
  "Makassar",
  "Manado",
];

export const POPULAR_TAGS = [
  "All Categories",
  "Legendary",
  "Viral TikTok",
  "Street Food",
  "Comfort Food",
  "Seafood",
  "Spicy",
  "Halal",
  "Heritage",
  "Late Night",
  "Breakfast",
  "Must Visit",
];
