import { PublicPlace, UserSavedPlace } from "../types";

export const INITIAL_PUBLIC_PLACES: PublicPlace[] = [
  {
    placeId: "ChIJ_haraku_ramen_halal",
    name: "Haraku Ramen",
    address: "Grand Indonesia West Mall Lt. 3A & Gandaria City, Jakarta",
    city: "Jakarta Selatan",
    lat: -6.1954,
    lng: 106.8217,
    rating: 4.8,
    saveCount: 95,
    topDishes: ["Creamy BARA Ramen", "Tori Paitan Ramen", "Karaage & Tempura"],
    tags: ["Ramen", "Halal", "Viral TikTok", "Jepang", "Pedas"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://vt.tiktok.com/ZSqFoDRbs/",
    vibesOrSummary: "Ramen halal kuah creamy bara pedas gurih viral dengan kuah kental kaldu ayam asli.",
  },
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    saveCount: 78,
    topDishes: ["Gulai Sapi Campur", "Gulai Sapi Daging", "Kerupuk Kulit Kuah"],
    tags: ["Street Food", "Viral TikTok", "Late Night", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    vibesOrSummary: "Gulai sapi legendaris tengah malam di trotoar Blok M dengan kuah gurih berempah khas.",
  },
  {
    placeId: "ChIJ77_claypot_popo",
    name: "Claypot Popo Melawai",
    address: "Jl. Melawai 9 No. 42, Blok M, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2435,
    lng: 106.7975,
    rating: 4.8,
    saveCount: 68,
    topDishes: ["Claypot Siram Telur Mentah", "Claypot Misua Tahu Telur Asin", "Es Teh Krisan"],
    tags: ["Comfort Food", "Cafe", "Viral TikTok", "Hidden Gem"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=claypot%20popo%20melawai",
    vibesOrSummary: "Comfort food bergaya peranakan disajikan mendidih di claypot tembikar panas.",
  },
  {
    placeId: "ChIJ44_warung_mak_beng",
    name: "Warung Mak Beng",
    address: "Jl. Hang Tuah No. 45, Sanur, Denpasar Selatan, Bali",
    city: "Bali",
    lat: -8.6758,
    lng: 115.2631,
    rating: 4.9,
    saveCount: 89,
    topDishes: ["Sup Kepala Ikan Bumbu Kuning", "Ikan Goreng Sambal Pedas"],
    tags: ["Legendary", "Seafood", "Pedas", "Hidden Gem"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=warung%20mak%20beng%20sanur",
    vibesOrSummary: "Warung legendaris sejak 1941 dengan hanya satu menu ikonik sup kepala ikan khas Sanur.",
  },
  {
    placeId: "ChIJ33_sate_maranggi_yetty",
    name: "Sate Maranggi Hj. Yetty",
    address: "Jl. Raya Cibungur, Bungursari, Purwakarta (Arah Bandung)",
    city: "Bandung",
    lat: -6.4715,
    lng: 107.4721,
    rating: 4.8,
    saveCount: 55,
    topDishes: ["Sate Maranggi Sapi", "Sambal Tomat Pedas Segar", "Es Kelapa Jeruk"],
    tags: ["Legendary", "Roadtrip", "Halal", "Viral TikTok"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=sate%20maranggi%20hj%20yetty",
    vibesOrSummary: "Sate sapi manis legit yang dipanggang arang sempurna dengan sambal tomat segar ulek.",
  },
  {
    placeId: "ChIJ22_nasgor_kebonsirih",
    name: "Nasi Goreng Kambing Kebon Sirih",
    address: "Jl. Kebon Sirih No. 3, Menteng, Jakarta Pusat",
    city: "Jakarta Pusat",
    lat: -6.1834,
    lng: 106.8302,
    rating: 4.6,
    saveCount: 37,
    topDishes: ["Nasi Goreng Kambing Jumbo", "Sate Kambing Bumbu Kecap", "Emping Melinjo"],
    tags: ["Street Food", "Legendaris", "Halal", "Late Night"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=nasi%20goreng%20kambing%20kebon%20sirih",
    vibesOrSummary: "Nasi goreng kambing wajan raksasa beraroma minyak samin dan rempah kapulaga tajam.",
  },
  {
    placeId: "ChIJ11_bebek_sinjay",
    name: "Bebek Sinjay Madura - Surabaya",
    address: "Jl. Rungkut Madya No. 133, Surabaya",
    city: "Surabaya",
    lat: -7.3235,
    lng: 112.7844,
    rating: 4.7,
    saveCount: 51,
    topDishes: ["Bebek Goreng Kremes", "Sambal Pencit Mangga Muda", "Nasi Hangat Daun Pisang"],
    tags: ["Pedas", "Viral TikTok", "Halal", "Comfort Food"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=bebek%20sinjay%20surabaya",
    vibesOrSummary: "Bebek renyah gurih bumbu rempah kuning dipadukan dengan pedas asamnya sambal pencit mangga.",
  },
  {
    placeId: "ChIJ55_gudeg_yudjum",
    name: "Gudeg Yu Djum Wijilan",
    address: "Jl. Wijilan No. 167, Panembahan, Kraton, Yogyakarta",
    city: "Yogyakarta",
    lat: -7.8049,
    lng: 110.3664,
    rating: 4.8,
    saveCount: 44,
    topDishes: ["Nasi Gudeg Kering Komplit", "Sambal Goreng Krecek Pedas", "Ayam Kampung Areh"],
    tags: ["Traditional", "Legendary", "Halal", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gudeg%20yu%20djum%20wijilan",
    vibesOrSummary: "Pusat gudeg kering asli Jogja dimasak kayu bakar dengan areh santan kental gurih.",
  }
];

export const INITIAL_USER_SAVED_PLACES: UserSavedPlace[] = [
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    recommendedDishes: ["Gulai Sapi Telur", "Kerupuk Kulit Kuah"],
    estimatedPrice: "Rp 15.000 - Rp 30.000",
    tags: ["Street Food", "Viral TikTok", "Late Night"],
    personalNotes: "Datang sebelum jam 8 malam biar ga antre panjang bareng anak-anak kantor.",
    savedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    vibesOrSummary: "Gulai sapi legendaris tengah malam di trotoar Blok M.",
  },
  {
    placeId: "ChIJ77_claypot_popo",
    name: "Claypot Popo Melawai",
    address: "Jl. Melawai 9 No. 42, Blok M, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2435,
    lng: 106.7975,
    rating: 4.8,
    sourceUrl: "https://www.tiktok.com/search?q=claypot%20popo%20melawai",
    recommendedDishes: ["Claypot Siram Telur Mentah", "Es Teh Krisan"],
    estimatedPrice: "Rp 40.000 - Rp 65.000",
    tags: ["Comfort Food", "Cafe", "Viral TikTok"],
    personalNotes: "Cobain saat cuaca hujan atau hangout santai sore di kawasan Blok M.",
    savedAt: new Date(Date.now() - 86400000).toISOString(),
    vibesOrSummary: "Comfort food peranakan hangat mendidih di claypot.",
  }
];

export const CITIES = [
  "Semua Kota",
  "Jakarta Selatan",
  "Jakarta Pusat",
  "Jakarta Barat",
  "Bandung",
  "Surabaya",
  "Bali",
  "Yogyakarta",
];

export const POPULAR_TAGS = [
  "Semua Kategori",
  "Street Food",
  "Viral TikTok",
  "Comfort Food",
  "Hidden Gem",
  "Halal",
  "Cafe",
  "Pedas",
  "Late Night",
  "Legendary",
];
