import { PublicPlace, UserSavedPlace } from "../types";

export const INITIAL_PUBLIC_PLACES: PublicPlace[] = [
  {
    placeId: "ChIJ_haraku_ramen_halal",
    name: "Haraku Ramen",
    address: "Grand Indonesia West Mall Lt. 3A & Gandaria City, Jakarta",
    city: "Jakarta Selatan",
    lat: -6.1954,
    lng: 106.8217,
    rating: 4.8,
    saveCount: 95,
    topDishes: ["Creamy BARA Ramen", "Tori Paitan Ramen", "Karaage & Tempura"],
    tags: ["Ramen", "Halal", "Viral TikTok", "Jepang", "Pedas"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://vt.tiktok.com/ZSqFoDRbs/",
    vibesOrSummary: "Halal ramen with rich, creamy spicy broth made from authentic slow-simmered chicken collagen.",
  },
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    saveCount: 78,
    topDishes: ["Gulai Sapi Campur", "Gulai Sapi Daging", "Kerupuk Kulit Kuah"],
    tags: ["Street Food", "Viral TikTok", "Late Night", "Halal"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    vibesOrSummary: "Legendary late-night sidewalk beef curry in Blok M with signature rich, aromatic spiced broth.",
  },
  {
    placeId: "ChIJ77_claypot_popo",
    name: "Claypot Popo Melawai",
    address: "Jl. Melawai 9 No. 42, Blok M, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2435,
    lng: 106.7975,
    rating: 4.8,
    saveCount: 68,
    topDishes: ["Claypot Siram Telur Mentah", "Claypot Misua Tahu Telur Asin", "Es Teh Krisan"],
    tags: ["Comfort Food", "Cafe", "Viral TikTok", "Hidden Gem"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=claypot%20popo%20melawai",
    vibesOrSummary: "Peranakan-style comfort dishes served piping hot in traditional clay pottery.",
  },
  {
    placeId: "ChIJ44_warung_mak_beng",
    name: "Warung Mak Beng",
    address: "Jl. Hang Tuah No. 45, Sanur, Denpasar Selatan, Bali",
    city: "Bali",
    lat: -8.6758,
    lng: 115.2631,
    rating: 4.9,
    saveCount: 89,
    topDishes: ["Sup Kepala Ikan Bumbu Kuning", "Ikan Goreng Sambal Pedas"],
    tags: ["Legendary", "Seafood", "Spicy", "Hidden Gem"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=warung%20mak%20beng%20sanur",
    vibesOrSummary: "Iconic culinary establishment since 1941 featuring a single celebrated fish head soup recipe.",
  },
  {
    placeId: "ChIJ33_sate_maranggi_yetty",
    name: "Sate Maranggi Hj. Yetty",
    address: "Jl. Raya Cibungur, Bungursari, Purwakarta (Arah Bandung)",
    city: "Bandung",
    lat: -6.4715,
    lng: 107.4721,
    rating: 4.8,
    saveCount: 55,
    topDishes: ["Sate Maranggi Sapi", "Sambal Tomat Pedas Segar", "Es Kelapa Jeruk"],
    tags: ["Legendary", "Roadtrip", "Halal", "Viral TikTok"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=sate%20maranggi%20hj%20yetty",
    vibesOrSummary: "Sweet and savory marinated beef skewers charcoal-grilled to perfection with fresh spicy tomato sambal.",
  },
  {
    placeId: "ChIJ22_nasgor_kebonsirih",
    name: "Nasi Goreng Kambing Kebon Sirih",
    address: "Jl. Kebon Sirih No. 3, Menteng, Jakarta Pusat",
    city: "Jakarta Pusat",
    lat: -6.1834,
    lng: 106.8302,
    rating: 4.6,
    saveCount: 37,
    topDishes: ["Nasi Goreng Kambing Jumbo", "Sate Kambing Bumbu Kecap", "Emping Melinjo"],
    tags: ["Street Food", "Legendary", "Halal", "Late Night"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=nasi%20goreng%20kambing%20kebon%20sirih",
    vibesOrSummary: "Giant wok fried rice infused with aromatic ghee (minyak samin) and cardamom spices.",
  },
  {
    placeId: "ChIJ11_bebek_sinjay",
    name: "Bebek Sinjay Madura - Surabaya",
    address: "Jl. Rungkut Madya No. 133, Surabaya",
    city: "Surabaya",
    lat: -7.3235,
    lng: 112.7844,
    rating: 4.7,
    saveCount: 51,
    topDishes: ["Bebek Goreng Kremes", "Sambal Pencit Mangga Muda", "Nasi Hangat Daun Pisang"],
    tags: ["Spicy", "Viral TikTok", "Halal", "Comfort Food"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=bebek%20sinjay%20surabaya",
    vibesOrSummary: "Crispy savory fried duck coated with yellow spiced crumbs paired with spicy young mango sambal.",
  },
  {
    placeId: "ChIJ55_gudeg_yudjum",
    name: "Gudeg Yu Djum Wijilan",
    address: "Jl. Wijilan No. 167, Panembahan, Kraton, Yogyakarta",
    city: "Yogyakarta",
    lat: -7.8049,
    lng: 110.3664,
    rating: 4.8,
    saveCount: 44,
    topDishes: ["Nasi Gudeg Kering Komplit", "Sambal Goreng Krecek Pedas", "Ayam Kampung Areh"],
    tags: ["Traditional", "Legendary", "Halal", "Must Visit"],
    lastUpdated: new Date().toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gudeg%20yu%20djum%20wijilan",
    vibesOrSummary: "The home of authentic dry gudeg wood-fired with rich savory coconut areh.",
  }
];

export const INITIAL_USER_SAVED_PLACES: UserSavedPlace[] = [
  {
    placeId: "ChIJb8n9_gltik_blokm",
    name: "Gultik Blok M",
    address: "Jl. Mahakam No. 28, Kramat Pela, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2443,
    lng: 106.7991,
    rating: 4.7,
    tasteRating: 5,
    visited: true,
    visitedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    sourceUrl: "https://www.tiktok.com/search?q=gultik%20blok%20m",
    recommendedDishes: ["Gulai Sapi Telur", "Kerupuk Kulit Kuah"],
    estimatedPrice: "Rp 15,000 - Rp 30,000",
    tags: ["Street Food", "Viral TikTok", "Late Night"],
    personalNotes: "Arrive before 8 PM to avoid the office rush hour lines. The savory spiced broth is incredible paired with crispy crackers!",
    savedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    vibesOrSummary: "Legendary late-night sidewalk beef curry in Blok M.",
  },
  {
    placeId: "ChIJ77_claypot_popo",
    name: "Claypot Popo Melawai",
    address: "Jl. Melawai 9 No. 42, Blok M, Jakarta Selatan",
    city: "Jakarta Selatan",
    lat: -6.2435,
    lng: 106.7975,
    rating: 4.8,
    tasteRating: 4,
    visited: false, // Wishlist
    sourceUrl: "https://www.tiktok.com/search?q=claypot%20popo%20melawai",
    recommendedDishes: ["Claypot Siram Telur Mentah", "Es Teh Krisan"],
    estimatedPrice: "Rp 40,000 - Rp 65,000",
    tags: ["Comfort Food", "Cafe", "Viral TikTok"],
    personalNotes: "Saved on wishlist for a cozy dinner on a rainy evening or when exploring Melawai.",
    savedAt: new Date(Date.now() - 86400000).toISOString(),
    vibesOrSummary: "Warm comfort food bubbling in hot clay pottery.",
  }
];

export const CITIES = [
  "All Cities",
  "Jakarta Selatan",
  "Jakarta Pusat",
  "Jakarta Barat",
  "Bandung",
  "Surabaya",
  "Bali",
  "Yogyakarta",
];

export const POPULAR_TAGS = [
  "All Categories",
  "Street Food",
  "Viral TikTok",
  "Comfort Food",
  "Hidden Gem",
  "Halal",
  "Cafe",
  "Spicy",
  "Late Night",
  "Legendary",
];
